name: lettutor
description: Final Project of Advance Mobile course.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter_localizations: 
    sdk: flutter

  flutter:
    sdk: flutter

  intl: ^0.18.0
  
  cupertino_icons: ^1.0.2
  adaptive_theme: ^3.4.0
  go_router: ^11.1.2
  
  hive: ^2.2.3

  logger: ^2.0.2+1
  
  injectable: ^2.3.0
  get_it: ^7.6.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  riverpod: ^2.4.3
  intl_translation: ^0.18.2
  dio: ^5.3.3
  awesome_dio_interceptor: ^1.0.0
  retrofit: ^4.0.1
  path_provider: ^2.1.1
  path: ^1.8.3
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  either_dart: ^1.0.0
  google_nav_bar: ^5.0.6
  flutter_provider: ^2.1.0
  palette_generator: ^0.3.3+3
  flutter_pdfview: ^1.3.2
  pdf: ^3.10.4
  url_launcher: ^6.1.14
  video_player: ^2.7.2
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4
  country_picker: ^2.0.21
  country_flags: ^2.1.1
  readmore: ^2.2.0
  timeago: ^3.5.0
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_calendar: ^23.1.41
  country_code_picker: ^3.0.0
  auto_size_text: ^3.0.0
  timer_count_down: ^2.2.2
  jitsi_meet_wrapper: ^0.2.0+1
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  custom_lint: ^0.5.4
  riverpod_generator: ^2.3.5


flutter_intl:
  enabled: true
  use_deferred_loading: true

flutter:

  # generate: true
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


