name: lettutor
description: Final Project of Advance Mobile course.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter_localizations: 
    sdk: flutter

  flutter:
    sdk: flutter

  intl: ^0.18.0
  
  cupertino_icons: ^1.0.2
  adaptive_theme: ^3.4.0
  go_router: ^11.1.2
  
  hive: ^2.2.3

  logger: ^2.0.2+1
  
  injectable: ^2.3.0
  get_it: ^7.6.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  riverpod: ^2.4.1
  intl_translation: ^0.18.2
  dio: ^5.3.3
  awesome_dio_interceptor: ^1.0.0
  retrofit: ^4.0.1
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter_intl:
  enabled: true
  use_deferred_loading: true

flutter:

  # generate: true
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


